---
- name: Install packages
  yum: name={{ item }} state=latest
  with_items:
    - emacs
    - screen
    - autoconf
    - automake
    - libtool
    - python-dev
  when: ansible_distribution == "CentOS"

- name: Install ubuntu packages
  apt: name={{ item }} state=latest
  with_items:
    - python-pip
    - emacs24
    - python-dev
    - libpq-dev
    - libxml2-dev
    - libxslt1-dev
    - libldap2-dev
    - libsasl2-dev
    - dh-autoreconf
    - dlocate
    - bison
    - flex
    - git
    - python-software-properties
    - software-properties-common
    - uuid-runtime
    - curl
  when: ansible_distribution == "Ubuntu"

- name: Install packages
  pip:
    name: six
    state: latest

- name: Set git username
  git_config:
    name: user.name
    scope: global
    value: "Hui Kang"

- name: Set git email
  git_config:
    name: user.email
    scope: global
    value: "kangh@us.ibm.com"

- name: Set git editor
  git_config:
    name: core.editor
    scope: global
    value: emacs

- sysctl:
    name: net.ipv4.neigh.default.gc_interval
    value: 3600
    sysctl_set: yes

- sysctl:
    name: net.ipv4.neigh.default.gc_stale_time
    value: 3600
    sysctl_set: yes

- sysctl:
    name: net.ipv4.neigh.default.gc_thresh3
    value: 8192
    sysctl_set: yes

- sysctl:
    name: net.ipv4.neigh.default.gc_thresh2
    value: 4096
    sysctl_set: yes

- sysctl:
    name: net.ipv4.neigh.default.gc_thresh1
    value: 2048
    sysctl_set: yes

- pam_limits:
    domain: root
    limit_type: soft
    limit_item: nofile
    value: 64000

- pam_limits:
    domain: root
    limit_type: hard
    limit_item: nofile
    value: 131070

#- copy:
#    src: resolv.conf
#    dest: /etc/resolv.conf
#    mode: 0644
