---
- name: Install packages
  yum: name={{ item }} state=latest
  with_items:
    - emacs
    - screen
    - autoconf
    - automake
    - libtool
    - python-dev
  when: ansible_distribution == "CentOS"

- name: Install ubuntu packages
  apt: name={{ item }} state=latest
  with_items:
    - python-pip
    - emacs24
    - python-dev
    - libpq-dev
    - libxml2-dev
    - libxslt1-dev
    - libldap2-dev
    - libsasl2-dev
  when: ansible_distribution == "Ubuntu"

- name: Install packages
  pip:
    name: six
    state: latest
