require_relative '../shared.rb'

Vagrant.configure("2") do |config|
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.ssh.password = 'vagrant'
  create_vm(config, name: 'openstack-rabbitmq', id: 1)
  create_vm(config, name: 'openstack-rabbitmq', id: 2)
  create_vm(config, name: 'sensu-rabbitmq', id: 3)
  create_vm(config, name: 'sensu-rabbitmq', id: 4)
end
