---

# Setup golang development environment

- name: Download GO binary
  get_url: url=https://storage.googleapis.com/golang/go1.10.5.linux-amd64.tar.gz dest=/root/go1.10.5.linux-amd64.tar.gz mode=0755 validate_certs=False

- name: Install GO
  unarchive:
    src: /root/go1.10.5.linux-amd64.tar.gz
    dest: /usr/local
    copy: no

- name: Add go bin to the PATH
  shell: echo 'export PATH="$PATH:/usr/local/go/bin:/go/bin"' >> /root/.bashrc

- name: Create GOPATH
  shell: echo 'export GOPATH="/go"' >> /root/.bashrc

- name: Ensure GOPATH directory exits
  file:
    path: "/go"
    state: "directory"
    recurse: yes

- name: Download go emacs mode
  git:
    repo: https://github.com/dominikh/go-mode.el.git
    dest: "{{ goModePath }}"
    accept_hostkey: yes

- name: Ensure emacs config directory exists
  file:
    path: /root/.emacs.d
    state: "directory"
    recurse: yes

- name: Copy over emacs file
  template:
    src: emacs-init.el.j2
    dest: /root/.emacs.d/init.el

- name: Create go src github.com exists
  file:
    path: /go/src/github.com
    state: "directory"
    recurse: yes

- name: Install go swagger
  shell: /usr/local/go/bin/go get -u github.com/go-swagger/go-swagger/cmd/swagger
  when: ansible_distribution == "Ubuntu"
