---
- name: Download ovs source tree
  git:
    repo: https://github.com/huikang/ovs.git
    dest: /root/ovs

- name: "Install packages to compile ovs"
  apt: pkg={{ item }} state=latest
  with_items:
    - git
    - autoconf
    - make
    - automake
    - libtool
    - uuid-runtime
  when: ansible_distribution == "Ubuntu"

- name: Install ansible
  pip:
    name: "{{ item }}"
    state: latest
  retries: 5
  with_items:
    - markupsafe
    - ansible
    - tox
    - netaddr
    - docker-py

#
# to build ovs datapath
# ./configure  --with-linux=/lib/modules/3.13.0-95-generic/build/
# make; make modules_install
#
