---
- debug: msg="OS familer is {{ ansible_os_family }}"
- debug: msg="OS distribution is {{ ansible_distribution }}"
- debug: msg="OS version is {{ ansible_distribution_release }}"

- include: centos_docker.yml
  when:
    - ansible_distribution == "CentOS"

- include: ubuntu_docker.yml
  when:
    - ansible_distribution == "Ubuntu"
