---
# file: non-coreos-site.yml

# Available roles: kolla

#- name: Prepare all nodes
#  hosts: all
#  roles:
#    - osprepare
#  tags:
#    - phase1

- name: Install docker
  hosts: all
  roles:
    - { role: docker,
        tags: docker,
        when: enable_docker | bool }

- name: Prepare hyper
  hosts: hyper
  roles:
    - golang
    - hyper
  tags:
    - hyper

- name: Prepare OSv host
  hosts: osv
  roles:
    - golang
    - qemu
    - osv
  tags:
    - osv

- name: Prepare OVN host
  hosts: ovn
  roles:
    - osprepare
    - ovn
  tags:
    - ovn

- name: Install kolla
  hosts: kolla

  roles:
    - kolla
  tags:
    - kolla

- name: Prepare docker
  hosts: docker-dev

  roles:
    - docker-dev
  tags:
    - docker-dev

- name: Heroku Go env
  hosts: heroku-dev

  roles:
    - heroku
  tags:
    - heroku

- name: GO program
  hosts: go-dev

  roles:
    - golang
  tags:
    - golang

- name: k8s cluster
  hosts: k8s
  roles:
    - golang
    - k8s
  tags:
    - k8s

- name: Oprofile
  hosts: oprofile
  roles:
    - oprofile
  tags:
    - oprofile

- name: Unikernel
  hosts: unikernel
  roles:
    - unikernel
    - qemu
  tags:
    - unikernel

- name: devstack
  hosts: devstack
  roles:
    - devstack
  tags:
    - devstack

- name: panda
  hosts: panda
  roles:
    - golang
    - kolla
    - panda
  tags:
    - panda
