---
# file: roles/kolla/tasks/osprepare.yml

# Demo installation for Kolla All-In-One

- name: Download kolla source code
  git:
    repo: https://github.com/openstack/kolla.git
    dest: /root/kolla

- name: Install pip
  shell: easy_install pip
  when: ansible_distribution_release == "vivid"

- name: Install ansible
  pip:
    name: "{{ item }}"
    state: latest
  retries: 5
  with_items:
    - markupsafe
    - ansible
    - tox

- name: Install required pip
  pip:
    requirements: /root/kolla/requirements.txt

- name: Install openstack client
  pip:
    name:  python-openstackclient
    state: latest

- name: Set the MountFlags option
  command: mount --make-shared /run

- name: Disable and stop libvirtd
  service:
    name: libvirtd
    state: stopped
    enabled: no
  ignore_errors: yes

- include: config-docker.yml

# - include: all-in-one.yml

- debug: msg="Now you can manually build kolla images"
